E-Sh4rk/EmeraldACE_web

files/list.json, files/pkmn/PutEggWithDesiredPIDInDaycareENG.txt
Adds a code to generate an egg with desired PID in the daycare in US Version
=> Add Daycare Code

files/list.json, files/pkmn/ChangePokerusOrigin.txt
hopefully I edited the json correctly this time
=> Add Code For Modifying Pkrs and Origins Data

files/misc/ChangeTrainerNameENG.txt, files/misc/ChangeTrainerNameGER.txt
=> Namechangediit

files_frlg/rng/tidsid.txt
Shao helped me write a TID\SID Code a while ago, and I've been pasting it in every time myself.
Used it multiple times successfully, should be good to add.
=> FRLG TID SID Change

files/misc/JPNChangeTIDSID.txt
@c-poole was kind enough to create a generator-compatible version of Sleipnir's Japanese TID\SID Code.
I added some helpful notes.
=> Add Translation of Sleipnir JAP TID SID Code.

files/rng/ChangePrngSeedNon-JAP.txt
Tested on SPA with 0x0599 Execution and it worked. Used RAM Viewer to confirm PRNG State change to 0x000005A0, for the memes :)
=> Make ChangePRNG Multi-Language

files/pkmn/ChangeEvs.txt
I was a bit confused about
* whether the stat changes would be applied immediately (without requiring level up)
* what the value of OTID is
* whether cur_hp represents the current number of HP EVs vs current HP stat value
Opening this PR to clarify a bit!
=> Improve ChangeEvs docstring

files/rng/ChangeFreezePrngSeedJAPThumb.txt
Please tell me if the code itself needs any changing or the warnings need to be clearer.
=> Added Thumb version of 'Change and freeze PRNG seed (JAP)'

files/rng/PutEggWithDesiredPIDInDaycareJAP.txt
Sorry for another pull request but I also had this code sitting around on my computer. Please note that the desired PID is intentionally stored in Box 5 as an egg PID of 0 is apparently not possible anyway. Like my other pull request, this is also a Thumb code.
=> Added Japanese version of 'Put EGG With Desired PID in Daycare'

files_frlg/exit.txt
**Disclosure: I did not develop this code, I pulled it from Sleipnir17's Pastebin**
Please let me know if this is fine.
=> Add exit code commonly used in grab ACE (FRLG)

files_frlg/RunScriptviaNPC.txt, files_frlg/misc/RunScriptViaNPC.txt
Finally got around to making this a proper code.
The way I have it laid out, it only works for English 1.0\1.1
I couldn't find symbols lists for the EU languages, but I didn't want to just sit on this and not do anything. So for now, its English only.
=> FRLG Code for Running Scripts via NPC

files/misc/ChangeSlot2Level.txt, files_frlg/misc/ChangeLevel.txt, files_frlg/misc/PIDorTIDCorrupt.txt
Added 2 codes for FRLG Grab ACE:
Perform PID/TID Corruption on Box 3 Slot 1 (Same slot as Mail Corruption, allows for multiple corruption types)
Change Level of Slot 6 Pokemon
and one Emerald ACE code:
Change Level of Slot 2 Pokemon
=> Some More Codes

doc/HiddenPowerHex.txt, files_frlg/pkmn/HiddenPowerEgg.txt
A stunning sequel to my previous code, but now with Custom IVs/Hidden Power types thanks to the extra length provided by the bootstrap (and some help from it_is_final in GCRI).
Pretty cool stuff!
=> Create Egg with Custom Hidden Power

files/list.json, files/misc/ChangeObjectEventScriptENG.txt, files/misc/ChangeObjectEventScriptFRA.txt, files/misc/ChangeObjectEventScriptGER.txt, files/misc/ChangeObjectEventScriptITA.txt, files/misc/ChangeObjectEventScriptSPA.txt
Added Change ObjectEvent Script Pointer code
=> Added Change ObjectEvent Script Pointer code

files_frlg/misc/CreatePokemon.txt, files_rs/pkmn/PokemonFromNothing.txt, files_rs/pkmn/PokemonFromNothingJAP.txt
Addresses issues stated in #40
=> Changes to Create Pokémon from Nothing codes across R/S and FR/LG

files_frlg/misc/EnableTutors.txt, files_frlg/pkmn/FatefulMew.txt
Added two new codes.
One that I made for capturing an Obedient Mew in FRLG, and the other adapting Sleipnir's Move Tutor code from MoveACE
=> Two new codes

files/list.json, files/misc/ChangeFullTrainerName.txt, files_frlg/misc/ChangeTrainerName.txt
* Port Sleipnir17's *Change trainer name* code for Emerald
* Upgrade FRLG code with a similar use of `LDM` and `STM`
=> Emerald - Change full trainer name

files_frlg/list.json, files_frlg/misc/RunScriptViaNPCJAP.txt
This is currently a draft pull request as I make it somewhat less hacky, and also to get thoughts on the code itself.
This code does not work identically to the English version of the code as it does not directly run the script address defined in the code, instead executing that address through the game's scripting system.
=> Add run script via NPC for JP

files_frlg/list.json, files_frlg/misc/CreateTradebackNPC.txt, files_frlg/pkmn/CreateAnyGiftPokemonBootstrapped.txt
created a couple of new codes, and fixed a slightly incorrect offset in the StartWildBattle code.
=> small fixes, and new additions

files_frlg/list.json, files_frlg/pkmn/FatefulMew_FR_ENG.txt, files_frlg/pkmn/FatefulMew_FR_FRA.txt, files_frlg/pkmn/FatefulMew_FR_GER.txt, files_frlg/pkmn/FatefulMew_FR_ITA.txt, files_frlg/pkmn/FatefulMew_FR_Rev1_ENG.txt, files_frlg/pkmn/FatefulMew_FR_SPA.txt, files_frlg/pkmn/FatefulMew_LG_ENG.txt, files_frlg/pkmn/FatefulMew_LG_FRA.txt, files_frlg/pkmn/FatefulMew_LG_GER.txt, files_frlg/pkmn/FatefulMew_LG_ITA.txt, files_frlg/pkmn/FatefulMew_LG_Rev1_ENG.txt, files_frlg/pkmn/FatefulMew_LG_SPA.txt
Finally did the legwork of opening up all the different language ROMs in HexEdit and finding the required script locations and offsets.
Not looking forward to doing the same for "Run Script via NPC," but I think its worthwhile.
Sure do wish we had those EU symbols lists 😅
=> Update Fateful Mew Encounter for all Languages/Versions

files/misc/UseMysteryEvent.txt
Added an ACE code to let the player use mystery event in Emerald. Only useful for my custom e-cards or ported official cards.
=> mystery event code for emerald us

files/exit.txt
Note that only the German and English codes are tested as of now.
=> Add shorter exit codes "TeleportFull" and "TeleportShort"

files/list.json, files/misc/ChangeGS.txt
This code is functional, but I will soon try to use the `gSetGameStat` function instead
=> Add Change Game Stat code

files_rs/list.json, files_rs/pkmn/ChangeLevel.txt, files_rs/pkmn/ReadOtid.txt, files_rs/pkmn/ReadPid.txt
* Fix address of `gPlayerParty` in *Read PID* and *Change Level* codes for French, Italian and Spanish versions
* Added *Read OTID* code
=> RS Read OTID code and fixes of `gPlayerParty` address

files/list.json, files/misc/ChangeTrainerGender.txt, files/misc/CopyOpponentPokemon.txt
- Added `Change Trainer Gender` code (from Sleipnir's Pastebin)
- Fixed "CertificateShortENG" instead of "CertificateShort{LANG}" exit in `Copy Opponent Pokemon` code
- Optimized `Copy Opponent Pokemon` code
=> Add `Change Trainer Gender` code

files_frlg/list.json, files_frlg/misc/RunScriptViaGlobalScriptContext.txt, files_frlg/misc/WarpViaGlobalScript.txt
- Added general purpose code that can be used to execute scripts at arbitrary addresses (this one works differently from "Run script via NPC" I promise)
- Added teleport code using this technique.
=> Added scripts that hijack sGlobalScriptContext for running custom scipts

files/list.json, files/pkmn/ChangePIDTID_ENG.txt, files_frlg/list.json, files_frlg/pkmn/ChangePIDTID_ENG.txt
This one is a pretty large code, and it has a bunch of special instructions around it in the comments.
=> Add "Change Pokémon PID or TID" code
