E-Sh4rk/EmeraldACE_web

files/misc/ChangeTrainerNameENG.txt
files/misc/ChangeTrainerNameGER.txt

Removes start=2 which exclusively edits data outside of the player name field. Adds instructions about needing to include the 0xFF character at the end as well as an example for a specific name and a link to the Bulbapedia page with the character encoding table.

name change instructions

---

files/rng/ChangeFreezePrngSeedJAPThumb.txt

Upon taking a further look at the code I noticed a few typos that made it through the first time. They're relatively minor but it doesn't sit well with me so I made this pull request fixing those typos.

Fix typos found in Change and freeze PRNG seed (JAP, Thumb)

---

files_frlg/pkmn/HiddenPowerEgg.txt

**DISCLAIMER: I wrote the guide being referred to in the link**
I noticed that the link to the bootstrap setup guide was slightly wrong so I made this pull request.
Should I also change the description from a 'bootstrap' to setting up a box 14 name since the 'bootstrap' linked there is more like a code to write the grab ACE exit to Box 14's name to get more space. Or a 'short exit' if you say.

Fix link to exit code setup for hidden power egg code (FRLG)

---

files/list.json
files/misc/AddItemWrongPocket.txt
files_frlg/list.json
files_frlg/misc/AddItemWrongPocket.txt

Added codes for Emerald and FRLG that insert an item into the wrong pocket

Item in Wrong Pocket Codes

---

files/list.json
files/misc/AddItemWrongPocket.txt
files_frlg/list.json
files_frlg/misc/AddItemWrongPocket.txt

Upgraded codes for Items in Wrong Pockets.
We can now get rid of the glitched slots generated with this code using `delete_mode`.

Item in Wrong Pocket Codes Upgrade

---

files/pkmn/PokemonFromNothingNoBootstrap.txt

With the information that all 16-bit numbers can be moved into a register in 4 instructions or less, I have modified the 'Create Pokémon from nothing (without exit code bootstrap)' code to allow creating a species from nothing with its hasSpecies flag set without needing an exit code bootstrap.
However I will be leaving this on draft as I have no idea what to do with the already existing bootstrapped version.

Set hasSpecies flag for Create Pokémon from nothing (without exit code bootstrap)

---

files/list.json
files/misc/MassClonePokemonJAPThumb.txt

This code allows extremely fast clone of a Pokémon (or empty space) in Box 9, Slot 1.
I had this code for quite a while now, which makes for an interesting demonstration of how `SWI` can be used in box name codes.
Unfortunately, this code is Japanese Thumb only but I have marked the `list.json` to only be listed for Japanese to reflect this.

Mass clone/declone Pokémon code (Japanese only)

---

files/misc/ChangeObjectEventScriptENG.txt
files/misc/ChangeObjectEventScriptFRA.txt
files/misc/ChangeObjectEventScriptGER.txt
files/misc/ChangeObjectEventScriptITA.txt
files/misc/ChangeObjectEventScriptSPA.txt

New calculation that makes `SUB` to take always 2 instructions
Remove `inaccurate_emu` (still works).

New ChangeObjectEventScript Offset Calc

---

files_frlg/misc/ChangeTrainerNameBootstrapped.txt
files_frlg/misc/EnableTutors.txt
files_frlg/pkmn/FatefulMew.txt
files_frlg/pkmn/FatefulMew_FR_ENG.txt
files_frlg/pkmn/FatefulMew_FR_FRA.txt
files_frlg/pkmn/FatefulMew_FR_GER.txt
files_frlg/pkmn/FatefulMew_FR_ITA.txt
files_frlg/pkmn/FatefulMew_FR_Rev1_ENG.txt
files_frlg/pkmn/FatefulMew_FR_SPA.txt
files_frlg/pkmn/FatefulMew_LG_ENG.txt
files_frlg/pkmn/FatefulMew_LG_FRA.txt
files_frlg/pkmn/FatefulMew_LG_GER.txt
files_frlg/pkmn/FatefulMew_LG_ITA.txt
files_frlg/pkmn/FatefulMew_LG_Rev1_ENG.txt
files_frlg/pkmn/FatefulMew_LG_SPA.txt
files_frlg/pkmn/HiddenPowerEgg.txt
files_frlg/rng/SeedChangeAndWarpBootstrapped.txt

As the Box 14 exit guide is now located in a different location, I have updated all of the references I can find in this pull request. Though I am also open to the idea of including this in the footer of the CodeGenerator (would need a separate pull request) alongside Sleipnir17's short exit guide.

Updated link to box 14 exit

---

files_frlg/misc/ChangeTrainerNameBootstrapped.txt
files_frlg/misc/EnableTutors.txt
files_frlg/pkmn/FatefulMew.txt
files_frlg/pkmn/FatefulMew_FR_ENG.txt
files_frlg/pkmn/FatefulMew_FR_FRA.txt
files_frlg/pkmn/FatefulMew_FR_GER.txt
files_frlg/pkmn/FatefulMew_FR_ITA.txt
files_frlg/pkmn/FatefulMew_FR_Rev1_ENG.txt
files_frlg/pkmn/FatefulMew_FR_SPA.txt
files_frlg/pkmn/FatefulMew_LG_ENG.txt
files_frlg/pkmn/FatefulMew_LG_FRA.txt
files_frlg/pkmn/FatefulMew_LG_GER.txt
files_frlg/pkmn/FatefulMew_LG_ITA.txt
files_frlg/pkmn/FatefulMew_LG_Rev1_ENG.txt
files_frlg/pkmn/FatefulMew_LG_SPA.txt
files_frlg/pkmn/HiddenPowerEgg.txt
files_frlg/pkmn/PIDEggFromNothing.txt
files_frlg/pkmn/ReadContestStats.txt
files_frlg/pkmn/ReadEvs.txt
files_frlg/rng/SeedChangeAndWarpBootstrapped.txt

I have changed the owner of the underlying GitHub repository for my website, and therefore the GitHub Pages links has changed for the main branch. The reason that these old links were still working is because I have kept a fork of the repo with Actions, and GitHub Pages enabled. However as the fork's gh-pages branch may get desynched from the main repository, I thought it would be worth it now to search and replace all instances of the old domain name (it-is-final.github.io) with (pomeg-letterbombers.github.io).

Change it-is-final.github.io links to pomeg-letterbombers.github.io for pokemon-ace-notes

---

files/list.json
files/misc/ChangeVar.txt
files_frlg/list.json
files_frlg/misc/ChangeVar.txt

* `SUB r11, pc, {var_offset} ?` takes at most 3 instructions for any variable on both games
* `MOV r12, {value} ?` takes at most 4 instructions for any 2 byte value
Then, since writing the variable takes one instruction more, we can confirm that all cases (at most, `3 + 4 + 1 = 8` instructions) fit with *CertificateFull* exits (space for 9 instructions) or *GrabACEExit* (space for 12 instructions)

Change Variable Code

---

files/misc/ChangeFlag.txt
files_frlg/misc/ChangeFlag.txt

Similar to code *Change Variable* generation tests:
* `SUB r11, pc, {flag_offset} ?` takes at most 3 instructions for any flag on both games
* `MOV r12, {flag_mask} ?` takes at most 4 instructions for any 2 byte value
Then, since the rest of the code takes at most 5 instructions, we can confirm that all cases (at most, `3 + 4 + 5 = 12` instructions) fit with *CertificateShort* exits (space for 13 instructions) or *GrabACEExit* (space for 12 instructions)

Change Flag - Multiple Flags

---

files/list.json
files/misc/DisableMusic.txt

I am only adding this for English atm, but I am 99% sure it'll work in its current form on all non-jpn languages. gDisableMusic is the same location in Eng, Spanish, French, German, and Italian. And the song 0x10F works to mute them all on load. 
I just don't have all those different language saves setup with bootstraps to make sure it runs to the right position in saveblock1. 
In Japanese gDisableMusic is at 0x3005b58 & I idk where savedMusic is in saveblock1.

Add disable music code

---

files/list.json
files/misc/CopyOpponentPokemon.txt

Due to charset limitations, I was unable to implement a loop or use `SWI` to copy the Pokemon(s), but the code works as expected

Add Copy Opponent Pokemon code

---

files/misc/CustomMassOutbreaks2.txt

This code was only working for maps with `group_id = 0` and `species < 256` because:
* `map_id`'s interpretation was incorrect. `map_id = map_num << 8 | group_id` in Sleipnir's list because `group_id` (`mapGroup`) is in the least significant byte of the `WarpData` structure
* The word that's being written should be `group_id << 24 | map_num << 16 | species` instead of `group_id << 16 | map_num << 8 | species`

Custom Mass Outbreaks Fix

---

files/pkmn/CallSetMonDataJAP.txt

Whoops, I didn't check that I have changed the uint32 properly before the previous PR got merged. -_-
Basically the wrong registers were being popped (they're not the same as the ones pushed which is not supposed to happen).

Fix erroneous POP instruction in Change Pokémon data code.

---

files_frlg/pkmn/FatefulMew.txt
files_frlg/pkmn/FatefulMew_FR_ENG.txt
files_frlg/pkmn/FatefulMew_FR_FRA.txt
files_frlg/pkmn/FatefulMew_FR_GER.txt
files_frlg/pkmn/FatefulMew_FR_ITA.txt
files_frlg/pkmn/FatefulMew_FR_Rev1_ENG.txt
files_frlg/pkmn/FatefulMew_FR_SPA.txt
files_frlg/pkmn/FatefulMew_LG_ENG.txt
files_frlg/pkmn/FatefulMew_LG_FRA.txt
files_frlg/pkmn/FatefulMew_LG_GER.txt
files_frlg/pkmn/FatefulMew_LG_ITA.txt
files_frlg/pkmn/FatefulMew_LG_Rev1_ENG.txt
files_frlg/pkmn/FatefulMew_LG_SPA.txt

Added some text to clarify the need to have cleared the Elite Four in order for this code to work.
It turns out some of the NPCs don't appear in the Indigo Plateau PokeCenter until after the E4 has been beaten at least once, causing this to fail.

Fateful Mew Text E4 Clarification

---

files/exit.txt

Add the short exit codes for sprite/animation ACE (requires a (meta)stable ACE) and the rare grab/swap ACE. There are variants which use the ROM (so these work without a BIOS) and ones that do use the BIOS and in turn clear up one 0xff filler.

Finally add short exit codes for Emerald

---

files_frlg/exit.txt
files_rs/exit.txt

Added a bunch of exit codes for jumping into a bunch of ROM addresses. These include:
- BIOS BX r0 (0x324).
- BIOS BX lr (0x354).
- BIOS BX lr (0x354) with extra instruction for grab ACE.
- ROM BX r0 (various addresses depending on game and language).
- ROM BX lr (various addresses depending on game and language).
- BIOS BX lr (0x354) with extra instruction for grab ACE.
I have added versions of these exits that start at Box 2, Box 6, and finally Box 10.
Edit: the issue with CodeGenerator has been fixed, thus the note about the exit code bug is no longer needed.

New exit codes for FR/LG and R/S

---

files_frlg/list.json
files_frlg/misc/CopySIDtoTID.txt
files_frlg/pkmn/Create6IVEgg.txt
files_frlg/pkmn/HiddenPowerEgg.txt
files_frlg/pkmn/ReadOTIDfromPartySlot4toPartySlot3.txt
files_frlg/pkmn/ReplacePokemonOT.txt

- Updated 6IV Egg/Hidden Power Egg codes to allow for custom origin game.
- Added step-by-step instructions to those codes for easier end-user experience.
- Added "Replace TID with SID" for quick SID checking (@claydolwithexplosion suggestion)
- Alter text in "Read OTID from Party Slot" code to clarify its only needed for checking SIDs from other saves.
- Added "Replace Pokemon OT with Trainer Name," which is useful for fixing generated Pokemon.
Have tested all of them myself, and they all use pc-relative addresses so they should be language\version agnostic.

Some Code Additions/Modifications

---

files/list.json
files/misc/RunScriptViaGlobalScriptContext.txt
files_frlg/misc/RunScriptViaGlobalScriptContext.txt
files_frlg/misc/Warp.txt
files_frlg/rng/SeedChangeAndWarpBootstrappedEN.txt
files_frlg/rng/SeedChangeAndWarpBootstrappedEU.txt
files_rs/list.json
files_rs/misc/RunViaScriptContext1.txt
files_rs/misc/Warp_Grab.txt
files_rs/rng/SeedChangeAndWarpGrabEN.txt
files_rs/rng/SeedChangeAndWarpGrabEU.txt

This pull request does the following:
Emerald:
- Add "Run script via GlobalScriptContext"
Unfortunately Emerald's address for GlobalScriptContext is inconvenient enough that I cannot directly port the teleport codes from the other versions to Emerald.
FireRed and LeafGreen:
- Updates "Teleport anywhere" and "Change PRNG seed and teleport (Bootstrapped)" to utilise the fact that GlobalScriptContext is already running when you are using the PC and overwrite the script pointer, skipping the extra set up needed for GlobalScriptContext.
- Updates "Run script via GlobalScriptContext" to now use `SCRIPT_MODE_BYTECODE`, and stackDepth 0.
Ruby and Sapphire:
- Add "Run script via ScriptContext1", "Teleport anywhere (Grab ACE)", and "Change PRNG seed and teleport (Grab ACE)".

GlobalScriptContext code
